"""sprint_6_liquidity_risk

Revision ID: 12c458666f1b
Revises: 542f0e8a7b2c
Create Date: 2026-07-07 19:11:38.496387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c458666f1b'
down_revision: Union[str, Sequence[str], None] = '542f0e8a7b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liquidity_assumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('methodology', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('configuration_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidity_assumptions_id'), 'liquidity_assumptions', ['id'], unique=False)
    op.create_index(op.f('ix_liquidity_assumptions_name'), 'liquidity_assumptions', ['name'], unique=True)
    op.create_table('concentration_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('limit_type', sa.String(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('warning_threshold_value', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concentration_limits_id'), 'concentration_limits', ['id'], unique=False)
    op.create_table('concentration_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('bucket_name', sa.String(), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('portfolio_weight', sa.Float(), nullable=False),
    sa.Column('position_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concentration_snapshots_id'), 'concentration_snapshots', ['id'], unique=False)
    op.create_table('liquidity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('assumption_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_market_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('weighted_liquidity_score', sa.Float(), nullable=False),
    sa.Column('estimated_liquidation_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('estimated_liquidation_cost_bps', sa.Float(), nullable=False),
    sa.Column('weighted_days_to_liquidate', sa.Float(), nullable=False),
    sa.Column('max_days_to_liquidate', sa.Integer(), nullable=False),
    sa.Column('very_low_liquidity_market_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('very_low_liquidity_weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assumption_id'], ['liquidity_assumptions.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidity_snapshots_id'), 'liquidity_snapshots', ['id'], unique=False)
    op.create_table('liquidity_position_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liquidity_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('liquidity_score', sa.Float(), nullable=False),
    sa.Column('liquidity_class', sa.String(), nullable=False),
    sa.Column('estimated_bid_ask_bps', sa.Float(), nullable=False),
    sa.Column('estimated_liquidation_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('model_daily_capacity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('participation_rate', sa.Float(), nullable=False),
    sa.Column('raw_days_to_liquidate', sa.Float(), nullable=False),
    sa.Column('estimated_trading_days_to_liquidate', sa.Integer(), nullable=False),
    sa.Column('liquidation_horizon_bucket', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('methodology', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], ),
    sa.ForeignKeyConstraint(['liquidity_snapshot_id'], ['liquidity_snapshots.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidity_position_results_id'), 'liquidity_position_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liquidity_position_results_id'), table_name='liquidity_position_results')
    op.drop_table('liquidity_position_results')
    op.drop_index(op.f('ix_liquidity_snapshots_id'), table_name='liquidity_snapshots')
    op.drop_table('liquidity_snapshots')
    op.drop_index(op.f('ix_concentration_snapshots_id'), table_name='concentration_snapshots')
    op.drop_table('concentration_snapshots')
    op.drop_index(op.f('ix_concentration_limits_id'), table_name='concentration_limits')
    op.drop_table('concentration_limits')
    op.drop_index(op.f('ix_liquidity_assumptions_name'), table_name='liquidity_assumptions')
    op.drop_index(op.f('ix_liquidity_assumptions_id'), table_name='liquidity_assumptions')
    op.drop_table('liquidity_assumptions')
    # ### end Alembic commands ###
