"""Add stress testing models

Revision ID: 542f0e8a7b2c
Revises: f85474701520
Create Date: 2026-07-07 09:48:37.151279

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '542f0e8a7b2c'
down_revision: str | Sequence[str] | None = 'f85474701520'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stress_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('scenario_type', sa.String(), nullable=False),
    sa.Column('is_predefined', sa.Boolean(), nullable=True),
    sa.Column('rate_2y_shock_bps', sa.Float(), nullable=False),
    sa.Column('rate_5y_shock_bps', sa.Float(), nullable=False),
    sa.Column('rate_10y_shock_bps', sa.Float(), nullable=False),
    sa.Column('rate_30y_shock_bps', sa.Float(), nullable=False),
    sa.Column('ig_spread_shock_bps', sa.Float(), nullable=False),
    sa.Column('hy_spread_shock_bps', sa.Float(), nullable=False),
    sa.Column('default_calculation_method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stress_scenarios_id'), 'stress_scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_stress_scenarios_name'), 'stress_scenarios', ['name'], unique=True)
    op.create_table('stress_test_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('calculation_method', sa.String(), nullable=False),
    sa.Column('base_market_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('stressed_market_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_loss_percent', sa.Float(), nullable=False),
    sa.Column('position_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['stress_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stress_test_runs_id'), 'stress_test_runs', ['id'], unique=False)
    op.create_table('stress_position_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stress_test_run_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('base_clean_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('stressed_clean_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_market_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('stressed_market_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('pnl_percent', sa.Float(), nullable=False),
    sa.Column('rate_shock_bps', sa.Float(), nullable=False),
    sa.Column('spread_shock_bps', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['stress_test_run_id'], ['stress_test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stress_position_results_id'), 'stress_position_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stress_position_results_id'), table_name='stress_position_results')
    op.drop_table('stress_position_results')
    op.drop_index(op.f('ix_stress_test_runs_id'), table_name='stress_test_runs')
    op.drop_table('stress_test_runs')
    op.drop_index(op.f('ix_stress_scenarios_name'), table_name='stress_scenarios')
    op.drop_index(op.f('ix_stress_scenarios_id'), table_name='stress_scenarios')
    op.drop_table('stress_scenarios')
    # ### end Alembic commands ###
