"""Add PortfolioRiskSnapshot

Revision ID: ca75d60a98bb
Revises: fe426ade3873
Create Date: 2026-07-07 22:21:03.255367

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ca75d60a98bb'
down_revision: str | Sequence[str] | None = 'fe426ade3873'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_risk_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('valuation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_market_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_unrealized_pnl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('weighted_ytm', sa.Float(), nullable=False),
    sa.Column('weighted_modified_duration', sa.Float(), nullable=False),
    sa.Column('weighted_convexity', sa.Float(), nullable=False),
    sa.Column('total_dv01', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('historical_var_95_1d', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('expected_shortfall_95_1d', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('parametric_var_95_1d', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('worst_stress_scenario', sa.String(length=100), nullable=True),
    sa.Column('worst_stress_loss', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('weighted_liquidity_score', sa.Float(), nullable=True),
    sa.Column('liquidation_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('liquidation_cost_bps', sa.Float(), nullable=True),
    sa.Column('weighted_days_to_liquidate', sa.Float(), nullable=True),
    sa.Column('max_days_to_liquidate', sa.Integer(), nullable=True),
    sa.Column('largest_issuer_concentration', sa.Float(), nullable=True),
    sa.Column('largest_sector_concentration', sa.Float(), nullable=True),
    sa.Column('overall_limit_status', sa.String(length=50), nullable=False),
    sa.Column('open_breach_count', sa.Integer(), nullable=False),
    sa.Column('acknowledged_breach_count', sa.Integer(), nullable=False),
    sa.Column('market_risk_model_status', sa.String(length=50), nullable=False),
    sa.Column('liquidity_model_type', sa.String(length=50), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'snapshot_date', name='uq_portfolio_snapshot_date')
    )
    op.create_index(op.f('ix_portfolio_risk_snapshots_id'), 'portfolio_risk_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_risk_snapshots_snapshot_date'), 'portfolio_risk_snapshots', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_risk_snapshots_snapshot_date'), table_name='portfolio_risk_snapshots')
    op.drop_index(op.f('ix_portfolio_risk_snapshots_id'), table_name='portfolio_risk_snapshots')
    op.drop_table('portfolio_risk_snapshots')
    # ### end Alembic commands ###
