"""add portfolio status and is active

Revision ID: cf4dd306ac1a
Revises: ebf2b8b01546
Create Date: 2026-07-10 15:33:08.417749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4dd306ac1a'
down_revision: Union[str, Sequence[str], None] = 'ebf2b8b01546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('portfolios', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('portfolios', sa.Column('status', sa.String(), nullable=True))
    op.execute("UPDATE portfolios SET is_active = TRUE WHERE is_active IS NULL")
    op.execute("UPDATE portfolios SET status = 'ACTIVE' WHERE status IS NULL")
    op.alter_column('portfolios', 'is_active', nullable=False)
    op.alter_column('portfolios', 'status', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'status')
    op.drop_column('portfolios', 'is_active')
    # ### end Alembic commands ###
