"""sprint_11_workflow_analytics

Revision ID: ebf2b8b01546
Revises: 4ec0a747785e
Create Date: 2026-07-09 15:15:24.642149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf2b8b01546'
down_revision: Union[str, Sequence[str], None] = '4ec0a747785e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('in_app_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_in_app_notifications_id'), 'in_app_notifications', ['id'], unique=False)
    op.create_table('saved_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('rate_2y_shock_bps', sa.Integer(), nullable=False),
    sa.Column('rate_5y_shock_bps', sa.Integer(), nullable=False),
    sa.Column('rate_10y_shock_bps', sa.Integer(), nullable=False),
    sa.Column('rate_30y_shock_bps', sa.Integer(), nullable=False),
    sa.Column('ig_spread_shock_bps', sa.Integer(), nullable=False),
    sa.Column('hy_spread_shock_bps', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_scenarios_id'), 'saved_scenarios', ['id'], unique=False)
    op.create_table('saved_scenario_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('executed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('base_market_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('stressed_market_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('pnl_impact', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['saved_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_scenario_runs_id'), 'saved_scenario_runs', ['id'], unique=False)
    op.add_column('breaches', sa.Column('under_review_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('breaches', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.add_column('breaches', sa.Column('review_notes', sa.String(), nullable=True))
    op.add_column('breaches', sa.Column('escalation_level', sa.Integer(), server_default='0', nullable=False))
    op.add_column('breaches', sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'breaches', 'users', ['assigned_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'breaches', type_='foreignkey')
    op.drop_column('breaches', 'sla_deadline')
    op.drop_column('breaches', 'escalation_level')
    op.drop_column('breaches', 'review_notes')
    op.drop_column('breaches', 'assigned_user_id')
    op.drop_column('breaches', 'under_review_at')
    op.drop_index(op.f('ix_saved_scenario_runs_id'), table_name='saved_scenario_runs')
    op.drop_table('saved_scenario_runs')
    op.drop_index(op.f('ix_saved_scenarios_id'), table_name='saved_scenarios')
    op.drop_table('saved_scenarios')
    op.drop_index(op.f('ix_in_app_notifications_id'), table_name='in_app_notifications')
    op.drop_table('in_app_notifications')
    # ### end Alembic commands ###
