"""Sprint 2 tables

Revision ID: f85474701520
Revises: 6bc2cf259103
Create Date: 2026-07-06 21:24:05.946332

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f85474701520'
down_revision: str | Sequence[str] | None = '6bc2cf259103'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('cusip', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('issuer_name', sa.String(), nullable=False),
    sa.Column('bond_name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('coupon_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('coupon_frequency', sa.String(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('day_count_convention', sa.String(), nullable=False),
    sa.Column('bond_type', sa.String(), nullable=False),
    sa.Column('credit_rating', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonds_cusip'), 'bonds', ['cusip'], unique=True)
    op.create_index(op.f('ix_bonds_id'), 'bonds', ['id'], unique=False)
    op.create_index(op.f('ix_bonds_isin'), 'bonds', ['isin'], unique=True)
    op.create_index(op.f('ix_bonds_ticker'), 'bonds', ['ticker'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('benchmark', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('current_clean_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'bond_id', name='uq_portfolio_bond_position')
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('clean_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('accrued_interest', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_consideration', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_bonds_ticker'), table_name='bonds')
    op.drop_index(op.f('ix_bonds_isin'), table_name='bonds')
    op.drop_index(op.f('ix_bonds_id'), table_name='bonds')
    op.drop_index(op.f('ix_bonds_cusip'), table_name='bonds')
    op.drop_table('bonds')
    # ### end Alembic commands ###
