"""sprint_7_risk_control

Revision ID: fe426ade3873
Revises: 12c458666f1b
Create Date: 2026-07-07 19:58:18.479797

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fe426ade3873'
down_revision: str | Sequence[str] | None = '12c458666f1b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_table('risk_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_value', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('warning_threshold', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('limit_threshold', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_limits_code'), 'risk_limits', ['code'], unique=True)
    op.create_index(op.f('ix_risk_limits_id'), 'risk_limits', ['id'], unique=False)
    op.create_table('risk_evaluation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('model_status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=False),
    sa.Column('evaluated_limit_count', sa.Integer(), nullable=False),
    sa.Column('breach_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_evaluation_runs_id'), 'risk_evaluation_runs', ['id'], unique=False)
    op.create_table('breaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('risk_limit_id', sa.Integer(), nullable=False),
    sa.Column('first_evaluation_run_id', sa.Integer(), nullable=False),
    sa.Column('latest_evaluation_run_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('observed_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('breach_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('acknowledgement_note', sa.String(), nullable=True),
    sa.Column('resolution_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['first_evaluation_run_id'], ['risk_evaluation_runs.id'], ),
    sa.ForeignKeyConstraint(['latest_evaluation_run_id'], ['risk_evaluation_runs.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['risk_limit_id'], ['risk_limits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breaches_id'), 'breaches', ['id'], unique=False)
    op.create_table('risk_limit_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_run_id', sa.Integer(), nullable=False),
    sa.Column('risk_limit_id', sa.Integer(), nullable=False),
    sa.Column('observed_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('utilization_percent', sa.Float(), nullable=True),
    sa.Column('result_status', sa.String(), nullable=False),
    sa.Column('breach_amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('metric_unit', sa.String(), nullable=False),
    sa.Column('calculation_source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['risk_evaluation_runs.id'], ),
    sa.ForeignKeyConstraint(['risk_limit_id'], ['risk_limits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_limit_results_id'), 'risk_limit_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_limit_results_id'), table_name='risk_limit_results')
    op.drop_table('risk_limit_results')
    op.drop_index(op.f('ix_breaches_id'), table_name='breaches')
    op.drop_table('breaches')
    op.drop_index(op.f('ix_risk_evaluation_runs_id'), table_name='risk_evaluation_runs')
    op.drop_table('risk_evaluation_runs')
    op.drop_index(op.f('ix_risk_limits_id'), table_name='risk_limits')
    op.drop_index(op.f('ix_risk_limits_code'), table_name='risk_limits')
    op.drop_table('risk_limits')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
