from enum import Enum


class MetricType(str, Enum):
    PORTFOLIO_MARKET_VALUE = "PORTFOLIO_MARKET_VALUE"
    PORTFOLIO_MODIFIED_DURATION = "PORTFOLIO_MODIFIED_DURATION"
    TOTAL_DV01 = "TOTAL_DV01"
    HISTORICAL_VAR_95_1D = "HISTORICAL_VAR_95_1D"
    PARAMETRIC_VAR_95_1D = "PARAMETRIC_VAR_95_1D"
    EXPECTED_SHORTFALL_95_1D = "EXPECTED_SHORTFALL_95_1D"
    WORST_STRESS_LOSS = "WORST_STRESS_LOSS"
    ISSUER_CONCENTRATION_MAX = "ISSUER_CONCENTRATION_MAX"
    SECTOR_CONCENTRATION_MAX = "SECTOR_CONCENTRATION_MAX"
    COUNTRY_CONCENTRATION_MAX = "COUNTRY_CONCENTRATION_MAX"
    RATING_CONCENTRATION_MAX = "RATING_CONCENTRATION_MAX"
    MAXIMUM_SINGLE_POSITION_WEIGHT = "MAXIMUM_SINGLE_POSITION_WEIGHT"
    LIQUIDITY_SCORE = "LIQUIDITY_SCORE"
    LIQUIDATION_COST_BPS = "LIQUIDATION_COST_BPS"
    MAX_DAYS_TO_LIQUIDATE = "MAX_DAYS_TO_LIQUIDATE"
    VERY_LOW_LIQUIDITY_EXPOSURE = "VERY_LOW_LIQUIDITY_EXPOSURE"
    LIQUIDITY_ADJUSTED_VAR = "LIQUIDITY_ADJUSTED_VAR"

class ScopeType(str, Enum):
    GLOBAL = "GLOBAL"
    PORTFOLIO = "PORTFOLIO"
    SECTOR = "SECTOR"
    ISSUER = "ISSUER"
    RATING = "RATING"
    COUNTRY = "COUNTRY"

class LimitDirection(str, Enum):
    MAXIMUM = "MAXIMUM"
    MINIMUM = "MINIMUM"

class LimitSeverity(str, Enum):
    WARNING = "WARNING"
    SOFT_LIMIT = "SOFT_LIMIT"
    HARD_LIMIT = "HARD_LIMIT"

class ResultStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    BREACH = "BREACH"
    NOT_EVALUATED = "NOT_EVALUATED"

class BreachStatus(str, Enum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"

class EvaluationOverallStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    BREACH = "BREACH"
    FAILED = "FAILED"
